### ISSUE TITLE
brew boxen-install bypasses system proxy configurations

### ISSUE THREAD

**Issue by jdraymon** [boxen/puppet-homebrew#33] opened 2014-02-11 02:38 UTC
Initial investigations show an unexpected response from your amazon server on the Net::HTTP request in boxen-monkeypatches.rb:25.  When I curl the URL given I get this XML response
```
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>542AC04223E7C175</RequestId>
    <HostId>
       RlehBneo53p7SInRRA2SuNRwLNOrnjR4K+7r/AKEo9/kxc+my013PfCvCg5ttJdy
    </HostId>
</Error>
```
And logs put into the body of the `|http|` block are never executed.

**Comment by jacobbednarz** [comment] 2016-10-24 03:29
Closing due to being over 12 months old. 

Please let me know if you can reproduce this now and I'll take a look.

**Closed by jacobbednarz** 2016-10-24 03:29 UTC
